# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$line_break\
$sudo\
$shell\
$character"""

[character]
success_symbol = '[\[I\]](bold green)'
error_symbol = '[\[✗\]](bold red)'
vimcmd_symbol = '[\[N\]](bold green)'
