# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = '[\[I\]](bold green)'
error_symbol = '[\[✗\]](bold red)'
vimcmd_symbol = '[\[N\]](bold green)'
